### ISSUE TITLE
 '/@modules/vue.js' does not provide an export named 'default' when using vitejs

### ISSUE THREAD

**Issue by Fanna1119** [phosphor-icons/vue#1]
I am trying to use `phosphor-vue` in a project that is set up with vitejs.

I tried to
```js
//vite.config.js
optimizeDeps: {
    exclude: ['dayjs', 'phosphor-vue']
  }
```
But I am still getting this.
>Uncaught SyntaxError: The requested module '/@modules/vue.js' does not provide an export named 'default'

procedure I followed.

`npm init vite-app myapp`

`npm install phosphor-vue`

In my template

```js
//app.vue
<template>
  <div>
    <PhHorse />
    <PhHeart :size="32" color="hotpink" weight="fill" />
    <PhCube />
  </div>
</template>

<script>
  import { PhHorse, PhHeart, PhCube } from "phosphor-vue";
  export default {
    name: "App",
    components: {
      PhHorse,
      PhHeart,
      PhCube
    }
  };
</script>


```

**Comment by rektdeckard** [comment]
Vite is [built for Vue 3.x only](https://github.com/vitejs/vite#getting-started), and this library is not yet compatible. We're planning to add support as a separate library eventually.

**Comment by asgomda** [comment]
I am using the latest version as at the time of this writing and I am still facing the same issue. Is there an update to this?
