### ISSUE TITLE
TypeScript errors: "no exported member..."

### ISSUE THREAD

**Issue by Clex1o1** [phosphor-icons/vue#19]
Hello, 

we've got some type errors while importing single icons in vue/nuxt with typescript. 
The import looks like this: 
```
<script lang="ts">
import { PhXCircle, PhCalendarBlank, PhClock } from 'phosphor-vue'
```
And the error in VS Code is: 

> Module '"phosphor-vue"' has no exported member 'PhXCircle'. Did you mean to use 'import PhXCircle from "phosphor-vue"' instead?ts(2614)

But the result works, with this error?

I found this import statement which i never saw like this before.
https://github.com/phosphor-icons/phosphor-vue/blob/4f28cd2e29ca8350b7a0283e241dac5546a8c631/phosphor-vue.d.ts#L3
I guess what i should do, is to pass the exported components from index.ts through the phoshor.d.ts, but this seems not to be valid in TypeScript.

**Comment by cn-2k** [comment]
Same here.

**Comment by dnlsndr** [comment]
This should be fixed with the next major version release. You can try it out by installing `@phosphor-icons/vue@next`.

**Comment by OfficialCRUGG** [comment]
Any solution for solving this issue with Vue 2 support?
