### ISSUE TITLE
npm ERR! Could not resolve dependency in Quasar vue

### ISSUE THREAD

**Issue by arbisyarifudin** [phosphor-icons/vue#27]
## DESCRIPTION

Hi, I just wanted to use phosphor vue for my quasar vue application.
But when I run ```npm install --save phosphor-vue@next```, it gets an error like below.
Does anyone know why? Is it because it doesn't support quasar vue or what? Thankyou.

## ERROR LOG
$ npm install phosphor-vue@next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: onero-crm-company-quasar@0.0.1
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.29" from @quasar/app@3.3.3
npm ERR!   node_modules/@quasar/app
npm ERR!     dev @quasar/app@"^3.0.0" from the root project
npm ERR!   peer vue@"3.2.37" from @vue/server-renderer@3.2.37
npm ERR!   node_modules/@vue/server-renderer
npm ERR!     @vue/server-renderer@"3.2.37" from vue@3.2.37
npm ERR!   9 more (emoji-mart-vue-fast, v-money3, vue-gtag, vue-i18n, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! phosphor-vue@"4.4.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@3.0.2
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.0.0 <3.0.3" from phosphor-vue@4.4.0
npm ERR!   node_modules/phosphor-vue
npm ERR!     phosphor-vue@"4.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ASUS\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Local\npm-cache\_logs\2022-07-15T02_44_38_791Z-debug-0.log

**Comment by n3-rd** [comment]
I'm not sure this project supports Vue 3

**Comment by hopkins385** [comment]
same here

**Comment by Wcamaly** [comment]
I have the same problem, any solution?

**Comment by n3-rd** [comment]
> I have the same problem, any solution?

You should probably look for an alternative, this project does not support Vue 3.

**Comment by dnlsndr** [comment]
Hi there, we're working on the next version of this library with native support for vue3. You can try out the newest release by running `npm install @phosphor-icons/vue@next`. Please note that the next branch is still in alpha and is bound to change.

This solution is for vue 3.
