### ISSUE TITLE
Global import broken

### ISSUE THREAD

**Issue by m-glass** [phosphor-icons/vue#34]
### 🐛 The bug

With the previous version `phosphor-vue`, global import was possible using

```ts
import { createApp } from 'vue'
import PhosphorVue from 'phosphor-vue'

const app = createApp(App)
app
  .use(PhosphorVue)

app.mount('#app')
```

With the new version, this is not possible anymore.

### 🛠️ To reproduce

https://stackblitz.com/edit/vue-dniokx?file=src/main.js

### 🌈 Expected behaviour

that switching to the new package works straightforward (just like written in the README.md)

**Comment by dnlsndr** [comment]
Thank's for letting us know. That must've gone under somewhere. Will see what I can do.

**Comment by dnlsndr** [comment]
I've now implemented global imports, check the release notes: https://github.com/phosphor-icons/vue/releases/tag/v2.1.4
