### ISSUE TITLE
"Error: EMFILE: too many open files... " when deploying Nuxt 3 app with Phosphor Icons to Netlify

### ISSUE THREAD

**Issue by miracleonyenma** [phosphor-icons/vue#35]
### 🐛 The bug

When I deploy my Nuxt 3 app which uses the @phosphor-icons/vue package to Netlify, the deployment is successful but when I visit the site, initially, I get an error:

![image](https://user-images.githubusercontent.com/42788603/230757941-f1ad0085-c2bf-4b1c-b0e9-cea9177366f7.png)

After some time, when I revisit the site, I get this error:

![image](https://user-images.githubusercontent.com/42788603/230757904-b75fc287-9a54-4528-a18b-63be158ed813.png)

It works okay in development and I've also tried building the app locally, Nuxt uses the "node-server" option and that works fine. 

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-tfqdxc?file=app.vue

### 🌈 Expected behaviour

The Icons should be displayed in production when deployed to Netlify and not crash the entire app.

**Comment by dnlsndr** [comment]
Sorry for getting back to you so late, aparrently I wasn't automatically set as an assignee. 
This error is interesting, I wouldn't know why netlify runs out of file descriptors. After all this library is really just a accumulation of pre-compiled components. 
Does your repro represent your project exactly or is it just a placeholder-repro for us to test against? 
Seems that you haven't really installed any packages in your repro, could you please provide the nuxt config as well as your package.json of your actual project where this issue occurs so I can better check what's going on?

**Comment by miracleonyenma** [comment]
Hey @dnlsndr, thanks so much for responding to this issue. 
Yes, it's a placeholder reproduction you can test against but the issue only appears during deployment. 
Here's [a repository with the code](https://github.com/miracleonyenma/nuxt-starter-tfqdxc) from [the StackBlitz reproduction](https://stackblitz.com/edit/nuxt-starter-tfqdxc?file=app.vue).
I deployed it on Netlify and you can [visit the site](https://classy-starlight-88f941.netlify.app/) to see the error.

**package.json**
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "HOST=0.0.0.0 nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.3.3"
  },
  "dependencies": {
    "@phosphor-icons/vue": "^2.0.1"
  }
}
```

**nuxt.config.ts**

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({

})
```

I believe the error can be addressed using this simple Nuxt project since the error occurs here. I hope that's okay. 

Thanks @dnlsndr

**Comment by dnlsndr** [comment]
I've implemented a compact build that's only a single file. This should help with your building issues. Check the release notes: https://github.com/phosphor-icons/vue/releases/tag/v2.1.4

**Comment by EmilyYond** [comment]
Hey @dnlsndr, I'm using 2.2.1 and also getting this error? Has something accidentally been reverted?

**Comment by EmilyYond** [comment]
@dnlsndr I have changed all my imports to be `import { PhBed, PhMapPin } from "@phosphor-icons/vue/compact"` and it worked for one build, but now it is erroring again. I deleted packages and reinstalled, but same issue. I'm running ` "@phosphor-icons/vue": "^2.2.1",` and deploying on vercel, which is just returning a 500 error:

```
[nuxt] [request error] [unhandled] [500] EMFILE: too many open files, open '/var/task/chunks/build/styles.mjs'
  at async open (node:internal/fs/promises:636:25)  
  at async readFile (node:internal/fs/promises:1246:14)  
  at async getSource (node:internal/modules/esm/load:46:14)  
  at async defaultLoad (node:internal/modules/esm/load:137:34)  
  at async ModuleLoader.load (node:internal/modules/esm/loader:396:7)  
  at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:45)  
  at async link (node:internal/modules/esm/module_job:78:21)
```

**Comment by kartsims** [comment]
@EmilyYond I am running into the same issue (deploying Nuxt on Vercel), did you manage to fix it? Is it necessary to import each icon? Thanks!

**Comment by EmilyYond** [comment]
@kartsims in the end I couldn't get around this, so am using the web package instead, so adding them into nuxt.config.ts like this:
```

        {
          rel: "preload",
          as: "style",
          href: "https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css",
          onload: "this.onload=null;this.rel='stylesheet'",
        },
        {
          rel: "preload",
          as: "style",
          href: "https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css",
          onload: "this.onload=null;this.rel='stylesheet'",
        },
        {
          rel: "preload",
          as: "style",
          href: "https://unpkg.com/@phosphor-icons/web@2.1.1/src/bold/style.css",
          onload: "this.onload=null;this.rel='stylesheet'",
        },
```
and then call it inline by doing `<i class="ph-bold ph-arrows-clockwise" />` for example
