### ISSUE TITLE
Not clone src/lib folder

### ISSUE THREAD

**Issue by hainguyen81** [phosphor-icons/vue#5]
The src/lib folder not cloning when I run npm install. So I could not build project
![image](https://user-images.githubusercontent.com/13741282/101317876-f06caf00-3891-11eb-8756-03fd136d206d.png)
![image](https://user-images.githubusercontent.com/13741282/101318096-55280980-3892-11eb-8856-34e2666f1025.png)

**Comment by rektdeckard** [comment]
Fixed with 47d1be7 and live with `v1.1.3`. You shouldn't have had a problem building, since the entry point is `dist/phosphor-vue.esm.js` and the bundled code doesn't rely on `src/`, it's just there for reference. But I grant that TypeScript would complain about missing modules.

**Comment by hainguyen81** [comment]
awsome! thanks for your support

**Comment by hainguyen81** [comment]
After I pull **v1.1.3** as you recommended, I compiled with errors like this:
![image](https://user-images.githubusercontent.com/13741282/101329054-76452600-38a3-11eb-93e0-cc851171a6d2.png)

I already included this module as Nuxt plugins.
![image](https://user-images.githubusercontent.com/13741282/101329164-9a086c00-38a3-11eb-8104-485ce2c30ece.png)

This's my **tsconfig.json**:
![image](https://user-images.githubusercontent.com/13741282/101329527-113e0000-38a4-11eb-8427-3e032fc4ced4.png)

But whenever I imported Phosphor components to use, I got these errors.
please help me. thanks

**Comment by hainguyen81** [comment]
Oh, my bad, I don't need to import the module's components to use. I already imported via entry module as Vue plugin.
So It already worked well.
Thanks much for your support
